### ISSUE TITLE
1주차 과제: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#1]
# 목표
자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기.

# 학습할 것
- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

# 마감일정 (이슈 닫히는 시간)
2022년 7월 24일 일 오후 11시 59분

**Comment by ku-kim** [comment]
이전에 정리했던 글 제출합니다.!

[Java의 컴파일과 실행 - kukim](https://kukim.tistory.com/24)

(아싸 1등..)

**Comment by nathan29849** [comment]
백기선 스터디 1주차 이슈 : https://github.com/whiteship/live-study/issues/1

**Comment by ikjo93** [comment]
두 개의 글로 나누어 정리해보았습니다!

+ <a href="https://ikjo.tistory.com/287">JVM이란 무엇인가? JVM 파헤쳐보기</a>
+ [Java 프로그램의 실행원리(feat. JVM)](https://ikjo.tistory.com/7)

작년에 대략적으로 작성한 글이 있긴 있었는데, 이번에 보니 너무 미흡해서 새로 갈아엎어 작성했습니다 ㅎㅎ 또한 JVM 구성 요소 중 하나인 가비지 컬렉터에 대한 부분은 나중에 별도로 정리해보고싶다는 생각이 들었습니다!!

**Comment by ak2j38** [comment]
1주차 과제 제출합니다.
[JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가](https://motivate-dev.tistory.com/36)

시간이 더 생기면 GC에 대해서도 따로 포스팅해서 공유하겠습니다 ㅠㅠ

**Comment by who-hoo** [comment]
[1주차 과제](https://velog.io/@who-hoo/%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%84%B0%EB%94%94-1%EC%A3%BC%EC%B0%A8-JVM) 제출합니다

**Comment by nohriter** [comment]
1주 차 과제 완료!
공부하면 공부할수록 모르는 게 많아지는 느낌을 받았습니다 😭
추후에 좀 더 자세히 학습해 보도록 하겠습니다.

https://nohriter.tistory.com/148

**Comment by leekm0310** [comment]
1주차 과제 제출합니다.
너무 당연하지만 한 두번 읽고 정리하는 걸로는 절대 익숙해질 수 없을거 같아요 열심히 하겠습니다 ㅠㅠ
[JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가](https://velog.io/@becolorful/JAVA-JVM%EC%9D%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%9E%90%EB%B0%94-%EC%BD%94%EB%93%9C%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%8B%A4%ED%96%89%ED%95%98%EB%8A%94-%EA%B2%83%EC%9D%B8%EA%B0%80)

**Comment by nathan29849** [comment]
1주차 과제 완료..!
[JVM을 통해 알아보는 자바 프로그램 실행과정](https://nathan29849.tistory.com/2)

**Comment by donggi-lee-bit** [comment]
안녕하시렵니까?
1주차 과제 제출합니다. 1주차 과제 해보면서 JVM에 대해 서로 알아가는 시간을 가져보니 좋았습니다.
[JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가](https://donggi.tistory.com/78)

**Comment by nathan29849** [comment]
1주차 과제 마감되었습니다!
미처 못내신 분들도 아래 댓글로 남겨주세요~

**Comment by mybloom** [comment]
[1주차 과제](https://devstep.tistory.com/76) 제출 합니다

**Comment by nathan29849** [comment]
[webhook test] closed issue comment
