### ISSUE TITLE
10주차 과제: 멀티쓰레드 프로그래밍

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#10]
# 목표
자바의 멀티쓰레드 프로그래밍에 대해 학습하세요.

# 학습할 것 (필수)
- Thread 클래스와 Runnable 인터페이스
- 쓰레드의 상태
- 쓰레드의 우선순위
- Main 쓰레드
- 동기화
- 데드락

# 마감일정 (이슈 닫히는 시간)
2022년 10월 2일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 10주차 이슈 : https://github.com/whiteship/live-study/issues/10

**Comment by ikjo93** [comment]
10주차 과제 제출합니다! 🎉 (지금 확인했는데, 10월 2일까지였네용? ㅋㅋ)

+ [프로세스 vs 스레드 그리고 멀티 태스킹 vs 멀티 스레드](https://ikjo.tistory.com/344)
+ [Java의 멀티 스레드(Multi-Thread) 프로그래밍에 대해 알아보자!](https://ikjo.tistory.com/345)

**Comment by donggi-lee-bit** [comment]
생각보다 내용 정리가 오래 걸리네요 😥

[10주차 멀티스레드](https://donggi.tistory.com/100)

**Comment by leekm0310** [comment]
쉽지 않네요.. 🤯
[멀티쓰레드 프로그래밍](https://velog.io/@becolorful/Java-멀티쓰레드-프로그래밍)
