### ISSUE TITLE
11주차 과제: Enum

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#11]
# 목표
자바의 열거형에 대해 학습하세요.

# 학습할 것 (필수)
- enum 정의하는 방법
- enum이 제공하는 메소드 (values()와 valueOf())
- java.lang.Enum
- EnumSet

# 마감일정 (이슈 닫히는 시간)
2022년 10월 9일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 11주차 이슈 : https://github.com/whiteship/live-study/issues/11

**Comment by ikjo93** [comment]
11주차 과제도 제출합니다! ✨ EnumSet에 대한 키워드는 이번에 정리하면서 처음 알게되었습니다 👍

+ [Java의 Enum에 대해 알아보자!](https://ikjo.tistory.com/347)

**Comment by donggi-lee-bit** [comment]
11주차 과제 제출합니다
https://donggi.tistory.com/103

**Comment by leekm0310** [comment]
11주차 과제 제출합니다. 틀린 내용이 많을 것 같은데 혹시라도 발견하신다면 언제든 지적해주세요!! 감사합니다 ㅠㅠ!!
https://velog.io/@becolorful/Java-Enum

**Comment by mybloom** [comment]
[11주차 과제 제출합니다.](https://devstep.tistory.com/86)
