### ISSUE TITLE
12주차 과제: 애노테이션

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#12]
# 목표
자바의 애노테이션에 대해 학습하세요.

# 학습할 것 (필수)
- 애노테이션 정의하는 방법
- `@retention`
- `@target`
- `@documented`
- 애노테이션 프로세서

# 마감일정 (이슈 닫히는 시간)
2022년 10월 16일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 12주차 이슈 : https://github.com/whiteship/live-study/issues/12

**Comment by ikjo93** [comment]
12주차 과제 제출합니다! 🥂 (애노테이션 어렵네요..)

+ [Java의 애노테이션(Annotation) 기초](https://ikjo.tistory.com/350)
  + [@SafeVarargs 언제 사용할까?](https://ikjo.tistory.com/349)
+ [애노테이션을 정의하는 방법과 메타 애노테이션의 종류](https://ikjo.tistory.com/351)

**Comment by leekm0310** [comment]
12주차 어노테이션 정리 제출 합니다.. 정말 너무 어려웠습니다..
https://velog.io/@becolorful/JAVA-Annotation
