### ISSUE TITLE
13주차 과제: I/O

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#13]
# 목표
자바의 Input과 Ontput에 대해 학습하세요.

# 학습할 것 (필수)
- 스트림 (Stream) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O
- InputStream과 OutputStream
- Byte와 Character 스트림
- 표준 스트림 (System.in, System.out, System.err)
- 파일 읽고 쓰기

# 마감일정 (이슈 닫히는 시간)
2022년 10월 23일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 13주차 이슈 : https://github.com/whiteship/live-study/issues/13

**Comment by ikjo93** [comment]
13주차 과제 제출합니다~🥂 (끝이 보인다...)
각각의 스트림 세부 특성을 다루기보다는 흐름만 잡았습니다

+ [Java의 입출력(I/O)에 대해 알아보자!](https://ikjo.tistory.com/354)

**Comment by leekm0310** [comment]
많이 늦었지만 제출합니다!
https://velog.io/@becolorful/JAVA-IO
