### ISSUE TITLE
2주차 과제: 자바 데이터 타입, 변수 그리고 배열

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#2]
# 목표
자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법을 익힙니다.

# 학습할 것
- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var

# 마감일정 (이슈 닫히는 시간)
2022년 7월 31일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 2주차 이슈 : https://github.com/whiteship/live-study/issues/2

**Comment by donggi-lee-bit** [comment]
안녕하시렵니까?
이번 주차 주제에 대해서 학습해보면서도 참 재미난 게 많았고
지금까지 잘 몰랐던 게 많았네요! ajax.

[자바 데이터 타입, 변수 그리고 배열](https://donggi.tistory.com/82)

**Comment by leekm0310** [comment]
2주차 내용을 정리했습니당
좀 더 자세히 공부할 필요가 있다고 생각했습니다.

[자바 데이터 타입, 변수 그리고 배열 ](https://velog.io/@becolorful/JAVA-%EC%9E%90%EB%B0%94-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%B0%B0%EC%97%B4)

**Comment by nohriter** [comment]
다들 이번 한주도 고생하셨습니다~ 

https://nohriter.tistory.com/149

**Comment by ku-kim** [comment]
고생 많이하셨습니다.!

https://kukim.tistory.com/25

**Comment by mybloom** [comment]
[2주차 과제](https://devstep.tistory.com/74) 제출합니다!

**Comment by nathan29849** [comment]
늦게나마 올립니다!

[2주차 과제](https://nathan29849.tistory.com/3)

**Comment by ikjo93** [comment]
2주차 과제 제출합니다!!
죄송합니다 많이 늦었네용.. 만만히 보고 마감기한 닥쳐서 하다가 큰 코 다쳤습니다...😥

https://ikjo.tistory.com/297
