### ISSUE TITLE
3주차 과제: 연산자

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#3]
# 목표
자바가 제공하는 다양한 연산자를 학습하세요.

# 학습할 것
- 산술 연산자
- 비트 연산자
- 관계 연산자
- 논리 연산자
- instanceof
- assignment(=) operator
- 화살표(->) 연산자
- 3항 연산자
- 연산자 우선 순위
- (optional) Java 13. switch 연산자

# 마감일정 (이슈 닫히는 시간)
2022년 8월 7일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 3주차 이슈 : https://github.com/whiteship/live-study/issues/3

**Comment by ku-kim** [comment]
3주차 제출합니다.!

https://kukim.tistory.com/26

**Comment by ikjo93** [comment]
2등! 3주차 과제 제출합니다 ㅎㅎ
저번주 지각으로(월요일 제출.. 😂) 이번에 만회코자 일찍 준비해봤습니다 ㅎㅎ

https://ikjo.tistory.com/304

**Comment by ak2j38** [comment]
3주차 제출합니다.
다들 화이팅!

[자바의 연산자에 대해서 알아보자](https://motivate-dev.tistory.com/37)

**Comment by nohriter** [comment]
https://nohriter.tistory.com/150

어느덧 3주차 ㅎㅎ 이번주도 다들 고생했어요~👏

**Comment by leekm0310** [comment]
머릿속이 어지럽네요🤯
[JAVA 연산자 정리](https://velog.io/@becolorful/Java-%EC%97%B0%EC%82%B0%EC%9E%90)

**Comment by nathan29849** [comment]
optional의 경우 java 13을 다루는 부분이라, lambda에 사용되는 이중 콜론(::) 연산자에 대한 정리로 대체하였습니다.

[Java 연산자](https://nathan29849.tistory.com/4)

모두 고생많으셨습니다!

**Comment by seokho-ham** [comment]
https://seokho-ham.github.io/java/whiteship-3/

**Comment by donggi-lee-bit** [comment]
많이 늦었습니다 ㅎㅎ;;
3주차 과제 제출입니다
[Java 연산자](https://donggi.tistory.com/87)
