### ISSUE TITLE
4주차 과제: 제어문

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#4]
# 목표
자바가 제공하는 제어문을 학습하세요.

# 학습할 것 (필수)
- 선택문
- 반복문

# 과제 (옵션)
### 과제 0. JUnit 5 학습하세요.
인텔리J, 이클립스, VS Code에서 JUnit 5로 테스트 코드 작성하는 방법에 익숙해 질 것.
이미 JUnit 알고 계신분들은 다른 것 아무거나!
[더 자바, 테스트](https://www.inflearn.com/course/the-java-application-test?inst=86d1fbb8) 강의도 있으니 참고하세요~

### 과제 1. live-study 대시 보드를 만드는 코드를 작성하세요.
깃헙 이슈 1번부터 18번까지 댓글을 순회하며 댓글을 남긴 사용자를 체크 할 것.
참여율을 계산하세요. 총 18회에 중에 몇 %를 참여했는지 소숫점 두 자리까지 보여줄 것.
[Github 자바 라이브러리](https://github-api.kohsuke.org/)를 사용하면 편리합니다.
깃헙 API를 익명으로 호출하는데 제한이 있기 때문에 본인의 깃헙 프로젝트에 이슈를 만들고 테스트를 하시면 더 자주 테스트할 수 있습니다.

### 과제 2. LinkedList를 구현하세요.
LinkedList에 대해 공부하세요.
정수를 저장하는 ListNode 클래스를 구현하세요.
ListNode add(ListNode head, ListNode nodeToAdd, int position)를 구현하세요.
ListNode remove(ListNode head, int positionToRemove)를 구현하세요.
boolean contains(ListNode head, ListNode nodeTocheck)를 구현하세요.

### 과제 3. Stack을 구현하세요.
int 배열을 사용해서 정수를 저장하는 Stack을 구현하세요.
void push(int data)를 구현하세요.
int pop()을 구현하세요.

### 과제 4. 앞서 만든 ListNode를 사용해서 Stack을 구현하세요.
ListNode head를 가지고 있는 ListNodeStack 클래스를 구현하세요.
void push(int data)를 구현하세요.
int pop()을 구현하세요.

### 과제 5. Queue를 구현하세요.
배열을 사용해서 한 번
ListNode를 사용해서 한 번

# 마감일정 (이슈 닫히는 시간)
2022년 8월 14일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 4주차 이슈 : https://github.com/whiteship/live-study/issues/4

**Comment by ku-kim** [comment]
4주차 제출합니다.

https://kukim.tistory.com/30

**Comment by ikjo93** [comment]
조금 이르지만 4주차 먼저 제출합니다!! ㅎㅎ (과제 옵션은 아직 못했는데 별도로 진행해본 후 공유해보겠습니다 👏)

https://ikjo.tistory.com/305

**Comment by nathan29849** [comment]
4주차 과제를 제출합니다(우선 필수만 완료하였고, 선택사항은 추후 학습 및 구현 후 댓글로 남기겠습니다!)
[4주차 과제](https://nathan29849.tistory.com/5)

**Comment by nathan29849** [comment]
webhook test

**Comment by ak2j38** [comment]
4주차 과제 제출합니다.(선택사항은 to be continue.....)
[4주차 과제](https://motivate-dev.tistory.com/38)

**Comment by donggi-lee-bit** [comment]
4주차 과제 제출합니다 (선택 사항은 학습 및 구현 후 댓글로 남길게요!)
[4주차 과제](https://donggi.tistory.com/88)

**Comment by realsigridjin** [comment]
4주차 과제 제출합니다.
[4주차 과제](https://sigridjineth.gitbook.io/the-awesome-sigrid-jin-encyclopedia/group-2/java/whiteship-4)

**Comment by leekm0310** [comment]
4주차 과제 제출합니다 선택사항은 구현하고 나서 댓글로 남기겠습니다
[4주차과제](https://velog.io/@becolorful/Java-제어문)

**Comment by seokho-ham** [comment]
4주차 과제 제출합니다 (선택사항은 추후 진행하겠습니다)
https://forkyy.tistory.com/11

선택사항
1. JUnit 학습 : [링크](https://forkyy.notion.site/0-JUnit5-f7972c3090104c1c90fbc6d1a77a0d12)

**Comment by ikjo93** [comment]
늦었지만 4주차 선택 과제도 제출해봅니다 ㅎㅎ

+ <a href="https://github.com/ikjo93/live-study-dashboard">라이브 스터드 대시보드 구현</a>
+ <a href="https://github.com/ikjo93/Data-Structure/tree/main/JavaStudy-whiteship/%EC%97%B0%EA%B2%B0%EB%A6%AC%EC%8A%A4%ED%8A%B8">연결리스트 구현</a>
+ <a href="https://github.com/ikjo93/Data-Structure/tree/main/JavaStudy-whiteship/%EC%8A%A4%ED%83%9D"> 배열 및 연결리스트를 통한 스택 구현</a>
+ <a href="https://github.com/ikjo93/Data-Structure/tree/main/JavaStudy-whiteship/%ED%81%90">배열 및 연결리스트를 통한 큐 구현</a>
