### ISSUE TITLE
5주차 과제: 클래스

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#5]
# 목표
자바의 Class에 대해 학습하세요.

# 학습할 것 (필수)
- 클래스 정의하는 방법
- 객체 만드는 방법 (new 키워드 이해하기)
- 메소드 정의하는 방법
- 생성자 정의하는 방법
- this 키워드 이해하기

# 과제 (옵션)
- int 값을 가지고 있는 이진 트리를 나타내는 Node 라는 클래스를 정의하세요.
- int value, Node left, right를 가지고 있어야 합니다.
- BinrayTree라는 클래스를 정의하고 주어진 노드를 기준으로 출력하는 bfs(Node node)와 dfs(Node node) 메소드를 구현하세요.
- DFS는 왼쪽, 루트, 오른쪽 순으로 순회하세요.

# 마감일정 (이슈 닫히는 시간)
2022년 8월 21일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 5주차 이슈 : https://github.com/whiteship/live-study/issues/5

**Comment by ku-kim** [comment]
5주차 제출합니다

https://kukim.tistory.com/31

**Comment by ikjo93** [comment]
5주차 과제 제출합니다! (선택 과제는 별도 구현한 뒤에 공유해볼게요! 😁)

https://ikjo.tistory.com/311

**Comment by ikjo93** [comment]
5주차 선택 과제도 제출해봅니다! 

https://github.com/ikjo93/Data-Structure/blob/main/이진트리/BinaryTree.java

+ 구현 내용
  + 노드 추가(상위 노드 보다 작으면 왼쪽 하위 노드, 크면 오른쪽 하위 노드)
  + 이진 트리 너비 우선 탐색(BFS)
  + 이진 트리 깊이 우선 탐색(DFS)
     + 전위 순회, 중위 순회, 후위 순회
+ 보완 예정
  + 노드 삽입 시마다 노드 정렬 기능(이진 검색 트리) 구현
  + 노드 삽입 시마다 밸런스 유지 기능 구현

**Comment by donggi-lee-bit** [comment]
5주차 과제 제출합니다!

https://donggi.tistory.com/89

**Comment by donggi-lee-bit** [comment]
5주차 선택 과제 제출합니다!

https://github.com/donggi-lee-bit/whitship_java/blob/main/src/main/java/donggi/whiteship_java/week5/BinaryTree.java

**Comment by nathan29849** [comment]
5주차 과제를 제출합니다
https://nathan29849.tistory.com/7

**Comment by leekm0310** [comment]
5주차 과제 제출합니다. 선택과제도 이후에 완료되면 제출하도록 하겠습니다.
https://velog.io/@becolorful/Java-클래스

**Comment by seokho-ham** [comment]
5주차 과제 제출합니다.
https://forkyy.tistory.com/12

**Comment by ak2j38** [comment]
5주차 과제입니다.
[5주차 과제](https://motivate-dev.tistory.com/41)
