### ISSUE TITLE
6주차 과제: 상속

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#6]
# 목표
자바의 상속에 대해 학습하세요.

# 학습할 것 (필수)
- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
- 추상 클래스
- final 키워드
- Object 클래스

# 마감일정 (이슈 닫히는 시간)
2022년 9월 4일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 6주차 이슈 : https://github.com/whiteship/live-study/issues/6

**Comment by ikjo93** [comment]
6주차 과제 제출합니다!! 😁 (첫 1등 🥂)

이번 과제는 3개의 글로 나누어 정리 및 학습해보았습니다. (개인적으로는 Object 클래스가 제일 빡셌습니다..😅)

정리하면서 새롭게 알아가는 내용들도 많아 유익했습니다 👍

+ [Java의 상속에 대해 파헤져보자!](https://ikjo.tistory.com/323)
+ [Java final 키워드의 여러가지 쓰임새](https://ikjo.tistory.com/322)
+ [Java의 Object 클래스가 제공하는 기능 분석](https://ikjo.tistory.com/319)

**Comment by leekm0310** [comment]
너무 간단하게 정리한것 같지만.. 일단 제출합니다.
https://velog.io/@becolorful/Java-상속

**Comment by nohriter** [comment]
https://nohriter.tistory.com/157

헷갈리는 개념들을 다시 공부할 수 있어 좋았습니다. 익조 글을 보니 다시 공부해야 할 것 같네요

**Comment by mybloom** [comment]
[6주차과제](https://devstep.tistory.com/77)  제출합니다.

**Comment by donggi-lee-bit** [comment]
두 개의 주제에 대해 밖에 정리하지 못했네요! 정리되는데로 업데이트 하겠습니다! https://donggi.tistory.com/92
[오버라이딩](https://donggi.tistory.com/93) [Java의 Dynamic Method Dispatch, Abstract class, final, Object class](https://donggi.tistory.com/94)

**Comment by nathan29849** [comment]
https://nathan29849.tistory.com/8
final 키워드와 Object는 따로 정리해서 올리도록 하겠습니다!
