### ISSUE TITLE
7주차 과제: 패키지

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#7]
# 목표
자바의 패키지에 대해 학습하세요.

# 학습할 것 (필수)
- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- -classpath 옵션
- 접근지시자

# 마감일정 (이슈 닫히는 시간)
2022년 9월 11일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 7주차 이슈 : https://github.com/whiteship/live-study/issues/7

**Comment by ikjo93** [comment]
7주차 과제도 제출합니다!! (접근 제어자는 예전에 정리했었던 걸로 대체했습니다 🥂)

자바 스터디도 벌써 절반이 다 됐네요..😅 다들 화이팅입니다!!

+ [Java의 패키지에 대해 알아보자! (feat. 클래스패스, import)](https://ikjo.tistory.com/327)
+ [캡슐화(정보 은닉)를 위한 Java의 접근 제어자 이해하기](https://ikjo.tistory.com/119)

**Comment by ak2j38** [comment]
7주차 과제입니다!
[7주차 과제](https://motivate-dev.tistory.com/42)

**Comment by nohriter** [comment]
벌써 절반이네요!  엄청 길다고 생각했는데 시간이 정말 빠른 것 같습니다. 다들 파이팅!!

https://nohriter.tistory.com/161

**Comment by leekm0310** [comment]
어려웠습니다. 반밖에 이해하지 못한것 같습니다. 그래도 정리한 내용을 올려봅니다 ㅠㅠ.. 파이팅..!
https://velog.io/@becolorful/Java-패키지

**Comment by seokho-ham** [comment]
7주차 과제 제출합니다.

https://forkyy.tistory.com/14

**Comment by mybloom** [comment]
[7주차과제](https://devstep.tistory.com/80) 제출합니다
