### ISSUE TITLE
8주차 과제: 인터페이스

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#8]
# 목표
자바의 인터페이스에 대해 학습하세요.

# 학습할 것 (필수)
- 인터페이스 정의하는 방법
- 인터페이스 구현하는 방법
- 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
- 인터페이스 상속
- 인터페이스의 기본 메소드 (Default Method), 자바 8
- 인터페이스의 static 메소드, 자바 8
- 인터페이스의 private 메소드, 자바 9

# 마감일정 (이슈 닫히는 시간)
2022년 9월 18일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 8주차 이슈 : https://github.com/whiteship/live-study/issues/8

**Comment by nohriter** [comment]
https://nohriter.tistory.com/166

빠르게 제출~

**Comment by ikjo93** [comment]
8주차도 클리어!! 🏋️‍♀️


+ [Java의 인터페이스에 대한 고찰](https://ikjo.tistory.com/334)

**Comment by leekm0310** [comment]
8주차 제출합니다!
https://velog.io/@becolorful/Java-인터페이스

**Comment by nathan29849** [comment]
8주차 제출합니다!
https://nathan29849.tistory.com/9

**Comment by ak2j38** [comment]
8주차 제출합니다. 늦어서 죄송합니다 ㅠ_ㅠ
[8주차 인터페이스](https://motivate-dev.tistory.com/43)
