### ISSUE TITLE
9주차 과제: 예외 처리

### ISSUE THREAD

**Issue by nathan29849** [Next-Squad/JavaStudy-whiteship#9]
# 목표
자바의 예외 처리에 대해 학습하세요.

# 학습할 것 (필수)
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법

# 마감일정 (이슈 닫히는 시간)
2022년 9월 25일 일 오후 11시 59분

**Comment by nathan29849** [comment]
백기선 스터디 9주차 이슈 : https://github.com/whiteship/live-study/issues/9

**Comment by ikjo93** [comment]
9주차 과제 제출합니다!! 🍂

+ [Java의 예외(Exception)에 대해 알아보자!](https://ikjo.tistory.com/340)

**Comment by donggi-lee-bit** [comment]
9주차 과제 제출합니다!

[예외 처리](https://donggi.tistory.com/96)

**Comment by ak2j38** [comment]
코테와 과제 일정에 파묻혀 지내느라 전에 정리했던 내용 제출합니다 ㅠ_ㅠ
[예외처리](https://velog.io/@ak2j38/토비의-스프링-예외)

**Comment by mybloom** [comment]
[예외처리](https://devstep.tistory.com/83) 제출

**Comment by donggi-lee-bit** [comment]
> [예외처리](https://devstep.tistory.com/83) 제출

링크를 누르면 권한이 없다고 나오네요 🧐

**Comment by leekm0310** [comment]
늦었습니다 ㅠㅅㅠ
[예외처리 정리](https://velog.io/@becolorful/Java-예외처리) 제출합니다
